/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package testuicomponents;

/**
 *
 * @author Administrateur
 */
public class TestDialog extends javax.swing.JDialog
{

    private int lastY = -1;

    /**
     * Creates new form TestDialog
     */
    public TestDialog(java.awt.Frame parent, boolean modal)
    {
        super(parent, modal);
        initComponents();
        setLocationByPlatform(true);

    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of
     * this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        jPanel1 = new javax.swing.JPanel();
        arcComponent1 = new testuicomponents.ArcComponent();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(26, 26, 26));

        arcComponent1.addMouseMotionListener(new java.awt.event.MouseMotionAdapter()
        {
            public void mouseDragged(java.awt.event.MouseEvent evt)
            {
                arcComponent1MouseDragged(evt);
            }
        });
        arcComponent1.addMouseWheelListener(new java.awt.event.MouseWheelListener()
        {
            public void mouseWheelMoved(java.awt.event.MouseWheelEvent evt)
            {
                arcComponent1MouseWheelMoved(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addComponent(arcComponent1, javax.swing.GroupLayout.DEFAULT_SIZE, 388, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(arcComponent1, javax.swing.GroupLayout.PREFERRED_SIZE, 249, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 49, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void arcComponent1MouseWheelMoved(java.awt.event.MouseWheelEvent evt)//GEN-FIRST:event_arcComponent1MouseWheelMoved
    {//GEN-HEADEREND:event_arcComponent1MouseWheelMoved
        if (evt.getWheelRotation() > 0)
        {
            arcComponent1.longer();
        } else
        {
            arcComponent1.shorter();
        }
    }//GEN-LAST:event_arcComponent1MouseWheelMoved

    private void arcComponent1MouseDragged(java.awt.event.MouseEvent evt)//GEN-FIRST:event_arcComponent1MouseDragged
    {//GEN-HEADEREND:event_arcComponent1MouseDragged
        if (lastY == -1)
        {
            lastY = evt.getY();
        } else
        {
            int y = evt.getY();
            if (y > lastY)
            {
                arcComponent1.shorter();
            } else if (y < lastY)
            {
                arcComponent1.longer();
            }
            lastY = y;
        }
    }//GEN-LAST:event_arcComponent1MouseDragged

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private testuicomponents.ArcComponent arcComponent1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
